..

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -26,29 +26,44 @@ concurrency:
   group: "pages"
   cancel-in-progress: true
 
-env: 
-  GUILD_NAME: ${{ vars.GUILD_NAME }}
-  GUILD_REALM: ${{ vars.GUILD_REALM }}
-  GUILD_REGION: ${{ vars.GUILD_REGION }}
-  GUILD_RAIDER_RANKS: "${{ vars.GUILD_RAIDER_RANKS }}"
-  GUILD_SOCIAL_RANKS: "${{ vars.GUILD_SOCIAL_RANKS }}"
-  GUILD_ALT_RANKS: "${{ vars.GUILD_ALT_RANKS }}"
-  ADDITIONAL_CHARACTERS: "${{ vars.ADDITIONAL_CHARACTERS }}"
-  RANK_OVERRIDE: "${{ vars.RANK_OVERRIDE }}"
-
 jobs:
   # Build job
   build-banshee:
     runs-on: ubuntu-latest
-
+    env: 
+      GUILD_NAME: ${{ vars.GUILD_NAME }}
+      GUILD_REALM: ${{ vars.GUILD_REALM }}
+      GUILD_REGION: ${{ vars.GUILD_REGION }}
+      GUILD_RAIDER_RANKS: "${{ vars.GUILD_RAIDER_RANKS }}"
+      GUILD_SOCIAL_RANKS: "${{ vars.GUILD_SOCIAL_RANKS }}"
+      GUILD_ALT_RANKS: "${{ vars.GUILD_ALT_RANKS }}"
+      ADDITIONAL_CHARACTERS: "${{ vars.ADDITIONAL_CHARACTERS }}"
+      RANK_OVERRIDE: "${{ vars.RANK_OVERRIDE }}"
     steps:
       - name: Checkout
         uses: actions/checkout@v3
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            echo "::set-output name=runner::yarn"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+            echo "::set-output name=runner::npx --no-install"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
           node-version: "16"
-          cache: ${{ steps.detect-package-manager.outputs.manager }}
+          cache: ${{ steps.detect-package-manager.outputs.manager }}x
       - name: Restore cache
         uses: actions/cache@v3
         with:
